### ISSUE TITLE
The build failed on jitpack

### ISSUE THREAD

**Issue by dazza5000** [robohorse/gpversionchecker#6]
Please see https://jitpack.io/com/github/robohorse/gpversionchecker/1.0.6/build.log

Start: Sat Sep 10 02:26:27 UTC 2016
Git:
1.0.6
commit ea62cd92b01ef588cef001438cf96164058d5b1c
Author: robohorse 
Date:   Tue Aug 9 00:40:51 2016 +0300

```
build 1.0.6
```

submodule status:

Run gradle build
Gradle build script

ERROR: Gradle wrapper not found. Please add. Using default gradle to build.

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

---
## Gradle 2.7

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.624s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/jitpack/build/build.gradle' line: 12
- What went wrong:
  A problem occurred evaluating root project 'build'.
  
  > Failed to apply plugin [id 'com.android.library']
  > Gradle version 2.10 is required. Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Found android library build file in .
Running: gradle clean -Pgroup=com.github.robohorse -Pversion=1.0.6 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/jitpack/build/build.gradle' line: 11
- What went wrong:
  A problem occurred evaluating root project 'build'.
  
  > Failed to apply plugin [id 'com.android.library']
  > Gradle version 2.10 is required. Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.752 secs
Gradle exit code 1
EXIT_CODE=1
2016-09-10T02:26:40.034007106Z
Exit code: 1
No build artifacts found

**Comment by robohorse** [comment]
Thanks for your issue. I updated library gradle version, BUT Google-Play now not showing app version on the web page. I will rework my library today/tomorrow and publish updated version. Thanks)

**Comment by dazza5000** [comment]
The current version is shown on the web page under additional information.

**Comment by robohorse** [comment]
Hm... in some cases it isn shown. Ok, i published version (1.0.7) with updated builders. Also i will think about all cases support.

**Comment by dazza5000** [comment]
Thank you!

**Comment by dazza5000** [comment]
Still having an issue on jitpack:

Start: Sun Sep 11 21:01:45 UTC 2016
Git:
1.0.7
commit 4734506165c83d46f5f1dd858cf9cdd8abc75942
Author: robohorse 
Date:   Sat Sep 10 15:01:32 2016 +0300

```
library updated
```

submodule status:

Run gradle build
Gradle build script

ERROR: Gradle wrapper not found. Please add. Using default gradle to build.

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

---

## Gradle 2.7

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.628s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/jitpack/build/build.gradle' line: 12
- What went wrong:
  A problem occurred evaluating root project 'build'.
  
  > Failed to apply plugin [id 'com.android.library']
  > Minimum supported Gradle version is 2.14.1.  Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Found android library build file in .
Running: gradle clean -Pgroup=com.github.robohorse -Pversion=1.0.7 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.jar

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/jitpack/build/build.gradle' line: 11
- What went wrong:
  A problem occurred evaluating root project 'build'.
  
  > Failed to apply plugin [id 'com.android.library']
  > Minimum supported Gradle version is 2.14.1.  Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.262 secs
Gradle exit code 1
EXIT_CODE=1
2016-09-11T21:01:59.762019323Z
Exit code: 1
No build artifacts found

**Comment by dazza5000** [comment]
I think we just need to bump the gradle version

**Comment by robohorse** [comment]
hm..
My root project gradle-wrapper.properties contains "distributionUrl=https://services.gradle.org/distributions/gradle-2.14.1-all.zip"

Which line in your gradle-wrapper.properties file?

> Failed to apply plugin [id 'com.android.library']
>  Minimum supported Gradle version is 2.14.1. Current version is 2.7. If using the gradle wrapper,  try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip

I think, that you need to check your gradle wrapper

**Comment by dazza5000** [comment]
Hmm...Must be a jitpack issue. That exception is from jitpack.
